services:
  - type: web
    name: mercenary-match3
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: commit
    maxShutdownDelaySeconds: 20
    envVars:
      - key: NODE_ENV
        value: production
